rosbridge_websocket:
  ros__parameters:
    address: "10.82.149.247"
    authenticate: false
    bson_only_mode: false
#    certfile: 'None'
    delay_between_messages: 0
    fragment_timeout: 600
    keyfile: None
    max_message_size: None
    params_glob: "''[*]''"
    port: 9090
    retry_startup_delay: 5
    services_glob: "''[*]''"
    topics_glob: "''[*]''"
    unregister_timeout: 10
    use_compression: false
    use_sim_time: false
#    websocket_ping_interval: ""
#    websocket_ping_timeout: ""



